apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: plaam/taskease-api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Production"
            - name: "AZURE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-id"
                  name: "azure-key-vault"
            - name: "AZURE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-secret"
                  name: "azure-key-vault"
            - name: "AZURE_TENANT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-tenant-id"
                  name: "azure-key-vault"
            - name: "AZURE_VAULT_NAME"
              valueFrom:
                secretKeyRef:
                  key: "azure-vault-name"
                  name: "azure-key-vault"
      restartPolicy: Always