apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11.3-management-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 15672
              name: "rbmq-mgmt-port"
            - containerPort: 5672
              name: "rbmq-msg-port"
          env:
            - name: "RABBITMQ_DEFAULT_PASS"
              valueFrom:
                secretKeyRef:
                  key: "password"
                  name: "rabbitmq-credentials"
            - name: "RABBITMQ_DEFAULT_USER"
              valueFrom:
                secretKeyRef:
                  key: "username"
                  name: "rabbitmq-credentials"

              
      restartPolicy: Always